---
title: "Orbitrap Preparation"
date: "`r Sys.Date()`"
header-includes:
     - \usepackage{longtable}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi=300, cache=FALSE,echo=F,warning=F,message=F,autodep=T,fig.height=3.5,fig.width=7,dpi=300)
library(knitr)
library(xtable)
```


```{r pict1}
# par(mfrow=c(1,3))


par(mar=c(0,0,3,0),xaxt="n",yaxt="n")
DLC::raster(files()[[1]],main=input$files$name[1],xlim=c(0,2*dim(files()[[1]])[1]))
if(!is.null(coord$x)){
  text(x=coord$x,y=coord$y,label=seq(length(coord$x)),col="red",pos = 3)
  symbols(x=coord$x,y=coord$y,fg="red",inches = F,add = T,rectangles = cbind(rep(input$stamp_width*10,length(coord$x)),rep(input$stamp_height*10,length(coord$x))))
}

if(length(files()) >= 2){
  par(mar=c(0,0,3,0),xaxt="n",yaxt="n")
  DLC::raster(files()[[2]],main=input$files$name[2],xlim=c(0,2*dim(files()[[2]])[1]))
  if(!is.null(coord$x)){
    text(x=coord$x,y=coord$y,label=seq(length(coord$x)),col="red",pos = 3)
    symbols(x=coord$x,y=coord$y,fg="red",inches = F,add = T,rectangles = cbind(rep(input$stamp_width*10,length(coord$x)),rep(input$stamp_height*10,length(coord$x))))
  }
}
if(length(files()) >= 3){
  par(mar=c(0,0,3,0),xaxt="n",yaxt="n")
  DLC::raster(files()[[3]],main=input$files$name[3],xlim=c(0,2*dim(files()[[3]])[1]))
  if(!is.null(coord$x)){
    text(x=coord$x,y=coord$y,label=seq(length(coord$x)),col="red",pos = 3)
    symbols(x=coord$x,y=coord$y,fg="red",inches = F,add = T,rectangles = cbind(rep(input$stamp_width*10,length(coord$x)),rep(input$stamp_height*10,length(coord$x))))
  }
}
```

```{r table,results="asis"}
# # kable(table.dim(),row.names = F)
truc = xtable(table.dim())
align(truc) = "rr|r|r|r|r|r|r|r|r"
print(truc,include.rownames = F,hline.after = -1:nrow(table.dim()),
      size = "\\fontsize{8pt}{30pt}\\selectfont",
      comment=F, tabular.environment='longtable')
# kable(table.dim())
```
  